
buildscript {
    apply from: './versions.gradle'
    addRepos(repositories)
    dependencies {
        classpath deps.android_maven_gradle_plugin
        classpath 'com.chenenyu:img-optimizer:1.2.0'

        classpath 'com.meituan.android.walle:plugin:1.1.6'

        if (isNeedPackage.toBoolean() && isUseBooster.toBoolean()) {
            classpath deps.booster.gradle_plugin
            classpath deps.booster.task_processed_res
            classpath deps.booster.task_resource_deredundancy
        }
    }

    repositories {
        maven { url "https://jitpack.io" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
    }
}

allprojects {
    addRepos(repositories)
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

repositories {
    google()
    maven { url "https://jitpack.io" }
    maven {url "https://maven.rongcloud.cn/repository/maven-releases/"}


}

