
apply plugin: 'com.xuexiang.xrouter'


configurations.each { configuration ->
    def dependencies = getProject().dependencies
    if (configuration.name == "implementation") {


        configuration.dependencies.add(dependencies.create(deps.xlibrary.xui))
        configuration.dependencies.add(dependencies.create(deps.androidx.appcompat))
        configuration.dependencies.add(dependencies.create(deps.androidx.recyclerview))
        configuration.dependencies.add(dependencies.create(deps.androidx.design))
        configuration.dependencies.add(dependencies.create(deps.glide))

        configuration.dependencies.add(dependencies.create(deps.xlibrary.xutil_core))

        configuration.dependencies.add(dependencies.create(deps.xlibrary.xupdate))

        configuration.dependencies.add(dependencies.create(deps.xlibrary.xhttp2))
        configuration.dependencies.add(dependencies.create(deps.rxjava2))
        configuration.dependencies.add(dependencies.create(deps.rxandroid))
        configuration.dependencies.add(dependencies.create(deps.okhttp3))
        configuration.dependencies.add(dependencies.create(deps.gson))

        configuration.dependencies.add(dependencies.create(deps.xlibrary.xpage_lib))

        configuration.dependencies.add(dependencies.create(deps.xlibrary.xrouter_runtime))
    }

    if (configuration.name == "annotationProcessor") {

        configuration.dependencies.add(dependencies.create(deps.xlibrary.xpage_compiler))

        configuration.dependencies.add(dependencies.create(deps.xlibrary.xrouter_compiler))
    }

}

configurations.all {
    resolutionStrategy.force deps.okhttp3
}